FROM node:18-alpine
# Install the application's dependencies into the node_modules's cache directory.
WORKDIR /client
COPY client/package*.json ./

COPY . .

ENTRYPOINT ["/bin/sh", "-c", "npm install && npm run start"]

