version: '3.8'
services:
  react_app:
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./client:/client
    environment:
      - REACT_APP_BACKEND_APP=http://localhost:3000
    depends_on:
      - node_app
  node_app:
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./server:/server
    environment:
      - MONGO_HOST=mongodb://mongo:27017
      - JWT_KEY=random_key
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata:
