version: '3.8'
services:
  react_app_prod:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./client:/client
    environment:
      - REACT_APP_BACKEND_APP=http://localhost:3000
    depends_on:
      - node_app_prod
  node_app_prod:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/server
    environment:
      - MONGO_HOST=mongodb://mongo_prod:27017
      - JWT_KEY=random_key
      - FRONTEND_ENDPOINT="http://localhost:3001"
    depends_on:
      - mongo_prod
  mongo_prod:
    image: mongo:3.6
    volumes:
      - mongodata-prod:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata-prod:
