FROM node:18-alpine
# Install the application's dependencies into the node_modules's cache directory.
WORKDIR /server
COPY server/package*.json ./

COPY . .

ENTRYPOINT ["/bin/sh", "-c", "npm install && npm run dev"]

